version: '3.8'

x-redis-common: &redis-common
  image: redis:7.2-alpine
  restart: unless-stopped
  command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redispass123}
  volumes:
    - redis_data:/data
  healthcheck:
    test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-redispass123}", "ping" ]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 30s
  networks:
    - general-network
  environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass123}

x-rabbitMq-common: &rabbitMq-common
  image: rabbitmq:4.2-management
  restart: unless-stopped
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin123
    - RABBITMQ_DEFAULT_VHOST=/
  volumes:
    - rabbitmq_data:/var/lib/rabbitmq
  networks:
    - general-network
  healthcheck:
    test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
    interval: 30s
    timeout: 10s
    retries: 5


services:
  db:
    image: postgres:17.5
    container_name: main_db
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3030
      POSTGRES_DB: main_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - general-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_for_rate_limit:
    <<: *redis-common
    container_name: redis-rate-limit
    ports:
      - "6379:6379"

  redis_for_user_service:
    <<: *redis-common
    container_name: redis_for_user_service
    ports:
      - "6377:6379"

  redis_for_book_service:
    <<: *redis-common
    container_name: redis_for_book_service
    ports:
      - "6372:6379"

  rabbitmq_user_notification:
    <<: *rabbitMq-common
    container_name: rabbitmq_for_user_notification_services
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  general-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data: