spring:
  application:
    name: BookService
  datasource:
    url: jdbc:postgresql://localhost:5436/main_db
    username: postgres
    password: 3030
    driver-class-name: org.postgresql.Driver
    simple-insert:
      user-book:
        schema: public
        table: users_books
  flyway:
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: false
    baseline-version: 1
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        transaction:
          jta:
            platform: none
    database: postgresql
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6372}
      password: ${REDIS_PASSWORD:redispass123}
      timeout: 10s
      connect-timeout: 10s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms
      book:
        ttl: 43200
  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin123
    virtual-host: /
    connection-timeout: 5000
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2.0
    queue:
      name: planning.from_book_service.queue
      message:
        ttl: 70000
      exchange:
        name: planning.from_book_service.exchange
      routing:
        key: planning.from_book_service.routing.key

google:
  books:
    api:
      key: ${GOOGLE_BOOK_API_KEY}
      url: https://www.googleapis.com/books/v1/volumes
      book: items(id,volumeInfo(title,authors,publisher,publishedDate,description,industryIdentifiers,pageCount,categories,language,mainCategory,imageLinks/thumbnail,infoLink))
    retry-name: externalService

open-library:
  search:
    api:
      url: https://openlibrary.org/search.json
      user-agent: BookApp/2.0 (books@example.com)
    editions-fields: "key,title,subtitle,publishers,publish_date,number_of_pages,isbn_13,isbn_10,lccn,oclc,
    language,ebook_access,ia,cover_i,physical_format,by_statement,description"
    retry-name: openlibraryRetry

server:
  forward-headers-strategy: framework
  port: 8081
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 1


logging:
  file:
    path: ./logs/bookService
    name: ${logging.file.path}/bookService.log
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 10
      total-size-cap: 5GB
      file-name-pattern: ${logging.file.path}/archived/bookService.%d{yyyy-MM-dd}.%i.log
  pattern:
    console: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %clr(%-5level) %logger{36} - %msg%n'
    file: '%d{dd.MM.yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'